config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'visitors#index'

  resources :students do
    get :subjects
  end

  resources :teachers do
    get :subjects
  end

  resources :payments

  resources :subject_items

  resources :subject_item_notes

  get 'report/subjects', to: 'reports#subjects'

  resources :visitors, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :student
  belongs_to :subject_item

  validates :student, :subject_item, presence: true
  validates :student, uniqueness: { scope: :subject_item }
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ActiveRecord::Base
  belongs_to :student, required: false, optional: true
  # belongs_to :student, optional: true
  validates :sum, :date, :student, presence: true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  has_many :participations, dependent: :delete_all
  has_many :subject_item_notes, dependent: :delete_all
  has_many :subject_items, dependent: :delete_all, through: :participations
  has_many :payments, dependent: :delete_all

  validates :first_name, :last_name, presence: true
  accepts_nested_attributes_for :subject_items
end

app/models/subject_item.rb
# frozen_string_literal: true

class SubjectItem < ApplicationRecord
  has_many :participations, dependent: :delete_all
  has_many :students, through: :participations
  has_many :subject_item_notes, dependent: :delete_all
  belongs_to :teacher
  belongs_to :student, optional: true

  validates :title, presence: true

  scope :not_assigned_or_assigned_to_teacher, ->(teacher) { where('teacher_id IS ? or teacher_id = ?', nil, teacher) }
end

app/models/subject_item_note.rb
# frozen_string_literal: true

class SubjectItemNote < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :subject_item, dependent: :delete
  validates :student_id, :subject_item_id, presence: true

  scope :for_subject_item, ->(subject_item) { where(subject_item: subject_item) }
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  TITLES = %w[Dr. Prof. TA].freeze
  has_many :subject_items, dependent: :delete_all

  validates :first_name, :last_name, presence: true
  validates :academic_title, inclusion: { in: TITLES }, presence: true

  accepts_nested_attributes_for :subject_items
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  # decent_configuration { strategy DecentExposure::StrongParametersStrategy }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      sanitized_params = %i[
        email
        password
        password_confirmation
      ]
      u.permit(sanitized_params)
    end
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  expose(:payments, attributes: :payment_params)
  expose :payments, -> { Payment.all }
  before_action :authenticate_user!
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  expose(:subject_items) { SubjectItem.includes(:teacher, :students) }
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  expose(:student, attributes: :student_params)
  expose(:student_subject_items) { student.subject_items }
  expose :students, -> { Student.all }

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.created', resource: 'Student')
    else
      render :new
    end
  end

  def update
    if student.update(student_params)
      redirect_to student_path(student), notice: I18n.t('shared.updated', resource: 'Student')
    else
      render :edit
    end
  end

  def destroy
    student.destroy
    redirect_to students_path, notice: I18n.t('shared.deleted', resource: 'Student')
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :birthdate, subject_item_ids: [])
  end
end

app/controllers/subject_item_notes_controller.rb
# frozen_string_literal: true

class SubjectItemNotesController < ApplicationController
  expose(:subject_item_note, attributes: :subject_item_note_params)
  expose :subject_item_notes, -> { SubjectItemNote.all }

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    if subject_item_note.save
      redirect_to subject_item_note_path(subject_item_note), notice: I18n.t('shared.created', resource: 'Subject Item Note')
    else
      render :new
    end
  end

  def update
    if subject_item_note.update(subject_item_note_params)
      redirect_to subject_item_note_path(subject_item_note), notice: I18n.t('shared.updated', resource: 'Subject Item Note')
    else
      render :edit
    end
  end

  def destroy
    subject_item.destroy
    redirect_to subject_item_notes_path, notice: I18n.t('shared.deleted', resource: 'Subject Item Note')
  end

  private

  def subject_item_note_params
    params.require(:subject_item_note).permit(:student_id, :subject_item_id, :value)
  end
end

app/controllers/subject_items_controller.rb
# frozen_string_literal: true

class SubjectItemsController < ApplicationController
  expose(:subject_item, attributes: :subject_item_params)
  expose :subject_items, -> { SubjectItem.all }

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    if subject_item.save
      redirect_to subject_item_path(subject_item), notice: I18n.t('shared.created', resource: 'Subject Item')
    else
      render :new
    end
  end

  def update
    if subject_item.update(subject_item_params)
      redirect_to subject_item_path(subject_item), notice: I18n.t('shared.updated', resource: 'Subject Item')
    else
      render :edit
    end
  end

  def destroy
    subject_item.destroy
    redirect_to subject_items_path, notice: I18n.t('shared.deleted', resource: 'Subject Item')
  end

  private

  def subject_item_params
    params.require(:subject_item).permit(:title, :teacher_id)
  end
end

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  before_action :authenticate_user!
  expose :teachers, -> { Teacher.all }
  expose(:teacher, attributes: :teacher_params)
  expose(:teacher_subject_items) { teacher.subject_items }
  skip_before_action :verify_authenticity_token

  def create
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.created', resource: 'Teacher')
    else
      render :new
    end
  end

  def update
    if teacher.update(teacher_params)
      redirect_to teacher_path(teacher), notice: I18n.t('shared.updated', resource: 'Teacher')
    else
      render :edit
    end
  end

  def destroy
    teacher.destroy
    redirect_to teachers_path, notice: I18n.t('shared.deleted', resource: 'Teacher')
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :academic_title, subject_item_ids: [])
  end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active?(*paths)
    'active' if paths.any? { |path| current_page?(path) }
  end
end

app/helpers/participations_helper.rb
# frozen_string_literal: true

module ParticipationsHelper
end

app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/helpers/subject_item_notes_helper.rb
# frozen_string_literal: true

module SubjectItemNotesHelper
end

app/helpers/subject_items_helper.rb
# frozen_string_literal: true

module SubjectItemsHelper
end

app/helpers/teachers_helper.rb
# frozen_string_literal: true

module TeachersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/students/_form.html.haml
= simple_form_for student do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :birthdate
  = f.association :subject_items, label_method: :title, value_method: :id, label: 'Subject Items', as: :check_boxes
  = link_to t('shared.back'), students_path, class: 'btn btn-secondary'
  = f.button :submit

app/views/students/_student.haml
%tr
  %td= student.first_name
  %td= student.last_name
  %td
    = link_to student_path(student), { title: t('shared.show') } do
      %button.btn.btn-primary
        = fa_icon "search"
    = link_to edit_student_path(student), { title: t('shared.edit') } do
      %button.btn.btn-primary
        = fa_icon "edit"
    = link_to student_path(student), { method: :delete, title: t('shared.delete') } do
      %button.btn.btn-primary
        = fa_icon "times"
    = link_to student_subjects_path(student), { title: t('shared.show_subject_items') } do
      %button.btn.btn-primary
        = fa_icon "list"

app/views/students/edit.html.haml
- breadcrumb :student, student
= render 'form'

app/views/students/index.html.haml
- breadcrumb :students
= link_to t('shared.add_new_item'), new_student_path, class: 'btn btn-secondary'
%table.table.table-default
  %thead
    %tr
      %th= t('student.columns.first_name')
      %th= t('student.columns.last_name')
      %th= t('shared.actions')
  %tbody
    =render students

app/views/students/new.html.haml
= render 'form'

app/views/students/show.html.haml
- breadcrumb :student, student
%table.table.table-default
  %tbody
    %tr
      %td= "#{t('student.columns.first_name')}:"
      %td= student.first_name
    %tr
      %td= "#{t('student.columns.last_name')}:"
      %td= student.last_name

= link_to t('shared.back'), students_path, class: 'btn btn-secondary'

app/views/students/subjects.html.haml
- breadcrumb :student_subjects, student
= student.decorate.full_name
%table.table.table-default
  %thead
    %tr
      %th= t('subject.title')
      %th= t('subjects.columns.avg_notes')
  %tbody
    - student_subject_items.each do |subject_item|
      %tr
        %td= subject_item.title
        %td= student.decorate.avg_notes(subject_item)
= link_to t('shared.back'), students_path, class: 'btn btn-secondary'

app/views/subject_item_notes/_form.html.haml
= simple_form_for(subject_item_note) do |f|
  = f.error_notification

  .form-inputs
    = f.association :student
    = f.association :subject_item

  .form-actions
    = f.button :submit, class: 'btn btn-secondary'

app/views/subject_item_notes/_subject_item_note.html.haml
%tr
  %td= subject_item_note.value
  %td= subject_item_note.decorate.student_full_name
  %td
    = link_to subject_item_note_path(subject_item_note), {title: t('shared.show')} do
      %button.btn.btn-primary
        =fa_icon "search"
    = link_to edit_subject_item_note_path(subject_item_note), {title: t('shared.edit')} do
      %button.btn.btn-primary
        =fa_icon "edit"
    = link_to subject_item_note_path(subject_item_note), {method: :delete, title: t('shared.delete')} do
      %button.btn.btn-primary
        =fa_icon "times"

app/views/subject_item_notes/edit.html.haml
%h1 Editing subject_item_note

= render 'form'

app/views/subject_item_notes/index.html.haml
%h1 Listing Subject Item Notes

%table.table.table-default
  %thead
    %tr
      %th Subject Item Note
      %th Student Name
      %th

  %tbody
    =render subject_item_notes
%br

= link_to t('shared.add_new_item'), new_subject_item_note_path, class: 'btn btn-secondary'

app/views/subject_item_notes/new.html.haml
%h1 New Subject Item Note

= render 'form'

= link_to 'Back', subject_item_notes_path, class: 'btn btn-primary'

app/views/subject_item_notes/show.html.haml
%p#notice= notice

%p
  %b Student:
  = subject_item_note.decorate.student_full_name
%p
  %b Subject item:
  = subject_item_note.subject_item

= link_to 'Edit', edit_subject_item_note_path(subject_item_note), class: 'btn btn-primary'

= link_to 'Back', subject_item_notes_path, class: 'btn btn-primary'

app/views/subject_items/_form.html.haml
= simple_form_for(subject_item) do |f|
  = f.error_notification
  .form-inputs
    = f.association :teacher, label_method: :last_name, value_method: :id, label: 'Teacher'
    .form-inputs
      = f.input :title
    .form-actions
      = f.button :submit

app/views/subject_items/_subject_item.html.haml
%tr
  %td= subject_item.title
  %td= subject_item.decorate.teacher_full_name
  %td
    = link_to subject_item_path(subject_item), {title: t('shared.show')} do
      %button.btn.btn-primary
        =fa_icon "search"
    = link_to edit_subject_item_path(subject_item), {title: t('shared.edit')} do
      %button.btn.btn-primary
        =fa_icon "edit"
    = link_to subject_item_path(subject_item), {method: :delete, title: t('shared.delete'), data: {confirm: "Are you sure?"}} do
      %button.btn.btn-primary
        =fa_icon "times"

app/views/subject_items/edit.html.haml
%h1 Editing Subject Item

= render 'form'

app/views/subject_items/index.html.haml
%h1 Listing Subject Items

%table.table.table-default
  %thead
    %tr
      %th Subject title
      %th Teacher name
      %th

  %tbody
    =render subject_items

= link_to 'New Subject item', new_subject_item_path, class: 'btn btn-secondary'

app/views/subject_items/new.html.haml
%h1 New Subject Item

= render 'form'

= link_to 'Back', subject_items_path, class: 'btn btn-secondary'

app/views/subject_items/show.html.haml
%p#notice= notice

%p
  %b Teacher:
  = subject_item.teacher

= link_to 'Edit', edit_subject_item_path(subject_item), class: 'btn btn-secondary'

= link_to 'Back', subject_items_path, class: 'btn btn-secondary'
%p
  %b Student:
  = subject_item.student

= link_to 'Edit', edit_subject_item_path(subject_item), class: 'btn btn-secondary'

= link_to 'Back', subject_items_path, class: 'btn btn-secondary'

app/views/teachers/_form.html.haml
= simple_form_for teacher do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :academic_title, collection: Teacher::TITLES, include_blank: false
  = f.association :subject_items, label_method: :title, value_method: :id, label: 'Subject Items', as: :check_boxes
  = link_to t('shared.back'), teachers_path, class: 'btn btn-secondary'
  = f.button :submit

app/views/teachers/_teacher.html.haml
%tr
  %td= teacher.first_name
  %td= teacher.last_name
  %td= teacher.academic_title
  %td
    = link_to teacher_path(teacher), { title: t('shared.show') } do
      %button.btn.btn-primary
        = fa_icon "search"
    = link_to edit_teacher_path(teacher), { title: t('shared.edit') } do
      %button.btn.btn-primary
        = fa_icon "edit"
    = link_to teacher_path(teacher), { method: :delete, title: t('shared.delete') } do
      %button.btn.btn-primary
        = fa_icon "times"
    = link_to teacher_subjects_path(teacher), { title: t('shared.show_subject_items') } do
      %button.btn.btn-primary
        = fa_icon "list"

app/views/teachers/edit.html.haml
- breadcrumb :teacher, teacher
= render 'form'

app/views/teachers/index.html.haml
- breadcrumb :teachers
= link_to t('shared.add_new_item'), new_teacher_path, class: 'btn btn-secondary'
%table.table.table-default
  %thead
    %tr
      %th= t('teacher.columns.first_name')
      %th= t('teacher.columns.last_name')
      %th= t('teacher.columns.academic_title')
      %th= t('shared.actions')
  %tbody
    = render teachers

app/views/teachers/new.html.haml
= render 'form'

app/views/teachers/show.html.haml
- breadcrumb :teacher, teacher
%table.table.table-default
  %tbody
    %tr
      %td= "#{t('teacher.columns.first_name')}:"
      %td= teacher.first_name
    %tr
      %td= "#{t('teacher.columns.last_name')}:"
      %td= teacher.last_name
    %tr
      %td= "#{t('teacher.columns.academic_title')}:"
      %td= teacher.academic_title
    %tr


= link_to t('shared.back'), teachers_path, class: 'btn btn-secondary'

app/views/teachers/subjects.html.haml
- breadcrumb :teacher_subjects, teacher
= teacher.decorate.full_name
%table.table.table-default
  %thead
    %tr
      %th= t('subject.title')
  %tbody
    - teacher_subject_items.each do |subject_item|
      %tr
        %td= subject_item.title
= link_to t('shared.back'), teachers_path, class: 'btn btn-secondary'