config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'visitors#index'

  resources :students do
    get :subjects
  end

  resources :teachers do
    get :subjects
  end

  resources :payments

  resources :subject_items

  resources :subject_item_notes

  get 'report/subjects', to: 'reports#subjects'

  resources :visitors, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :student
  belongs_to :subject_item

  validates :student, :subject_item, presence: true
  validates :student, uniqueness: { scope: :subject_item }
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ActiveRecord::Base
  belongs_to :student, required: false, optional: true
  # belongs_to :student, optional: true
  validates :sum, :date, :student, presence: true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  has_many :participations, dependent: :delete_all
  has_many :subject_item_notes, dependent: :delete_all
  has_many :subject_items, dependent: :delete_all, through: :participations
  has_many :payments, dependent: :delete_all

  validates :first_name, :last_name, presence: true
  accepts_nested_attributes_for :subject_items
end

app/models/subject_item.rb
# frozen_string_literal: true

class SubjectItem < ApplicationRecord
  has_many :participations, dependent: :delete_all
  has_many :students, through: :participations
  has_many :subject_item_notes, dependent: :delete_all
  belongs_to :teacher
  belongs_to :student, optional: true

  validates :title, presence: true

  scope :not_assigned_or_assigned_to_teacher, ->(teacher) { where('teacher_id IS ? or teacher_id = ?', nil, teacher) }
end

app/models/subject_item_note.rb
# frozen_string_literal: true

class SubjectItemNote < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :subject_item, dependent: :delete
  validates :student_id, :subject_item_id, presence: true

  scope :for_subject_item, ->(subject_item) { where(subject_item: subject_item) }
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  TITLES = %w[Dr. Prof. TA].freeze
  has_many :subject_items, dependent: :delete_all

  validates :first_name, :last_name, presence: true
  validates :academic_title, inclusion: { in: TITLES }, presence: true

  accepts_nested_attributes_for :subject_items
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  # decent_configuration { strategy DecentExposure::StrongParametersStrategy }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      sanitized_params = %i[
        email
        password
        password_confirmation
      ]
      u.permit(sanitized_params)
    end
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  expose(:payments, attributes: :payment_params)
  expose :payments, -> { Payment.all }
  before_action :authenticate_user!
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  expose(:subject_items) { SubjectItem.includes(:teacher, :students) }
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  expose(:student, attributes: :student_params)
  expose(:student_subject_items) { student.subject_items }
  expose :students, -> { Student.all }

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.created', resource: 'Student')
    else
      render :new
    end
  end

  def update
    if student.update(student_params)
      redirect_to student_path(student), notice: I18n.t('shared.updated', resource: 'Student')
    else
      render :edit
    end
  end

  def destroy
    student.destroy
    redirect_to students_path, notice: I18n.t('shared.deleted', resource: 'Student')
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :birthdate, subject_item_ids: [])
  end
end

app/controllers/subject_items_controller.rb
# frozen_string_literal: true

class SubjectItemsController < ApplicationController
  expose(:subject_item, attributes: :subject_item_params)
  expose :subject_items, -> { SubjectItem.all }

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    if subject_item.save
      redirect_to subject_item_path(subject_item), notice: I18n.t('shared.created', resource: 'Subject Item')
    else
      render :new
    end
  end

  def update
    if subject_item.update(subject_item_params)
      redirect_to subject_item_path(subject_item), notice: I18n.t('shared.updated', resource: 'Subject Item')
    else
      render :edit
    end
  end

  def destroy
    subject_item.destroy
    redirect_to subject_items_path, notice: I18n.t('shared.deleted', resource: 'Subject Item')
  end

  private

  def subject_item_params
    params.require(:subject_item).permit(:title, :teacher_id)
  end
end

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  before_action :authenticate_user!
  expose :teachers, -> { Teacher.all }
  expose(:teacher, attributes: :teacher_params)
  expose(:teacher_subject_items) { teacher.subject_items }
  skip_before_action :verify_authenticity_token

  def create
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.created', resource: 'Teacher')
    else
      render :new
    end
  end

  def update
    if teacher.update(teacher_params)
      redirect_to teacher_path(teacher), notice: I18n.t('shared.updated', resource: 'Teacher')
    else
      render :edit
    end
  end

  def destroy
    teacher.destroy
    redirect_to teachers_path, notice: I18n.t('shared.deleted', resource: 'Teacher')
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :academic_title, subject_item_ids: [])
  end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active?(*paths)
    'active' if paths.any? { |path| current_page?(path) }
  end
end

app/helpers/participations_helper.rb
# frozen_string_literal: true

module ParticipationsHelper
end

app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/helpers/subject_item_notes_helper.rb
# frozen_string_literal: true

module SubjectItemNotesHelper
end

app/helpers/subject_items_helper.rb
# frozen_string_literal: true

module SubjectItemsHelper
end

app/helpers/teachers_helper.rb
# frozen_string_literal: true

module TeachersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/participations/_form.html.haml
= simple_form_for(@participation) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user

  .form-actions
    = f.button :submit

app/views/participations/edit.html.haml
%h1 Editing participation

= render 'form'

= link_to 'Show', @participation

= link_to 'Back', participations_path

app/views/participations/index.html.haml
%h1 Listing participations

%table
  %thead
    %tr
      %th User
      %th
      %th
      %th

  %tbody
    - @participations.each do |participation|
      %tr
        %td= participation.user
        %td= link_to 'Show', participation
        %td= link_to 'Edit', edit_participation_path(participation)
        %td= link_to 'Destroy', participation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Participation', new_participation_path

app/views/participations/new.html.haml
%h1 New participation

= render 'form'

= link_to 'Back', participations_path

app/views/participations/show.html.haml
%p#notice= notice

%p
  %b User:
  = @participation.user

= link_to 'Edit', edit_participation_path(@participation)

= link_to 'Back', participations_path

app/views/payments/_payment.html.haml
- payments.each do |payment|
  %tr
    %td= payment.student.decorate.full_name
    %td= payment.decorate.convert_sum_to_currency
    %td= payment.date
    %td= payment.decorate.format_tuition_fee_to_date

app/views/payments/index.html.haml
- breadcrumb :payments
.payments
  .payment-item
    %table.table.table-default#products
      %thead
        %tr
          %th= t('payment.student.columns.decorate.full_name')
          %th= t('payment.columns.sum')
          %th= t('payment.columns.date')
          %th= t('payment.columns.tuition_fee')
      %tbody
        =render 'payment'

app/views/payments/show.html.haml
- breadcrumb :payment, payment
%table.table.table-default
  %tbody
    %tr
      %td= "#{t('payment.columns.student')}:"
      %td= payment.student.decorate.full_name
    %tr
      %td= "#{t('payment.columns.sum')}:"
      %td= payment.decorate.convert_sum_to_currency
    %tr
      %td= "#{t('payment.columns.date')}:"
      %td= payment.date
    %tr
      %td= "#{t('payment.columns.tution_fee')}:"
      %td= payment.decorate.formatted_tuition

= link_to t('shared.back'), payments_path, class: 'btn btn-secondary'

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user

= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_user_path(@user)

= link_to 'Back', users_path