config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'visitors#index'

  resources :students do
    get :subjects
  end

  resources :teachers do
    get :subjects
  end

  resources :payments

  resources :subject_items

  resources :subject_item_notes

  get 'report/subjects', to: 'reports#subjects'

  resources :visitors, only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :student
  belongs_to :subject_item

  validates :student, :subject_item, presence: true
  validates :student, uniqueness: { scope: :subject_item }
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ActiveRecord::Base
  belongs_to :student, required: false, optional: true
  # belongs_to :student, optional: true
  validates :sum, :date, :student, presence: true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  has_many :participations, dependent: :delete_all
  has_many :subject_item_notes, dependent: :delete_all
  has_many :subject_items, dependent: :delete_all, through: :participations
  has_many :payments, dependent: :delete_all

  validates :first_name, :last_name, presence: true
  accepts_nested_attributes_for :subject_items
end

app/models/subject_item.rb
# frozen_string_literal: true

class SubjectItem < ApplicationRecord
  has_many :participations, dependent: :delete_all
  has_many :students, through: :participations
  has_many :subject_item_notes, dependent: :delete_all
  belongs_to :teacher
  belongs_to :student, optional: true

  validates :title, presence: true

  scope :not_assigned_or_assigned_to_teacher, ->(teacher) { where('teacher_id IS ? or teacher_id = ?', nil, teacher) }
end

app/models/subject_item_note.rb
# frozen_string_literal: true

class SubjectItemNote < ApplicationRecord
  belongs_to :student, optional: true
  belongs_to :subject_item, dependent: :delete
  validates :student_id, :subject_item_id, presence: true

  scope :for_subject_item, ->(subject_item) { where(subject_item: subject_item) }
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  TITLES = %w[Dr. Prof. TA].freeze
  has_many :subject_items, dependent: :delete_all

  validates :first_name, :last_name, presence: true
  validates :academic_title, inclusion: { in: TITLES }, presence: true

  accepts_nested_attributes_for :subject_items
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  expose(:payments, attributes: :payment_params)
  expose :payments, -> { Payment.all }
  before_action :authenticate_user!
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  expose(:subject_items) { SubjectItem.includes(:teacher, :students) }
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  expose(:student, attributes: :student_params)
  expose(:student_subject_items) { student.subject_items }
  expose :students, -> { Student.all }

  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.created', resource: 'Student')
    else
      render :new
    end
  end

  def update
    if student.update(student_params)
      redirect_to student_path(student), notice: I18n.t('shared.updated', resource: 'Student')
    else
      render :edit
    end
  end

  def destroy
    student.destroy
    redirect_to students_path, notice: I18n.t('shared.deleted', resource: 'Student')
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :birthdate, subject_item_ids: [])
  end
end

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  before_action :authenticate_user!
  expose :teachers, -> { Teacher.all }
  expose(:teacher, attributes: :teacher_params)
  expose(:teacher_subject_items) { teacher.subject_items }
  skip_before_action :verify_authenticity_token

  def create
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.created', resource: 'Teacher')
    else
      render :new
    end
  end

  def update
    if teacher.update(teacher_params)
      redirect_to teacher_path(teacher), notice: I18n.t('shared.updated', resource: 'Teacher')
    else
      render :edit
    end
  end

  def destroy
    teacher.destroy
    redirect_to teachers_path, notice: I18n.t('shared.deleted', resource: 'Teacher')
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :academic_title, subject_item_ids: [])
  end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active?(*paths)
    'active' if paths.any? { |path| current_page?(path) }
  end
end

app/helpers/participations_helper.rb
# frozen_string_literal: true

module ParticipationsHelper
end

app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/helpers/subject_item_notes_helper.rb
# frozen_string_literal: true

module SubjectItemNotesHelper
end

app/helpers/subject_items_helper.rb
# frozen_string_literal: true

module SubjectItemsHelper
end

app/helpers/teachers_helper.rb
# frozen_string_literal: true

module TeachersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .about.pull-left
      = link_to 'About', root_path
    %ul#footer_nav.pull-right
      = link_to "https://github.com/katguz3485/ror_task-master" do
        %span.accent.fa.fa-github{"aria-label" => "github"}
      = link_to "https://www.linkedin.com/in/kguzik" do
        %span.accent.fa.fa-linkedin{"aria-label" => "linkedin"}

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  %a.navbar-brand{:href => root_path} RoR Task
  %button.navbar-toggler{"aria-controls" => "navbarColor01", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarColor01", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarColor01.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        = link_to t('navbar.students'), students_path
        %li.nav-item.active
          = link_to t('navbar.teachers'), teachers_path
        %li.nav-item.active
          = link_to t('navbar.payments'), payments_path
        %li.nav-item.active
          = link_to t('navbar.subject_items'), subject_items_path
        %li.nav-item.active
          = link_to t('navbar.subject_item_notes'), subject_item_notes_path
        %li.dropdown.active
          = link_to t('navbar.reports'), class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', role: 'button' do
            = t('navbar.reports')
            %span.caret
          %ul.dropdown-menu
            %li.nav-item.active
              = link_to t('navbar.reports_subjects'), report_subjects_path
    %ul.nav.navbar-nav.ml-auto
      - if user_signed_in?
        %li.btn.btn-secondary.my-2.my-sm-0
          = link_to t('navbar.logout'), destroy_user_session_path, method: :delete
      - else
        %li.btn.btn-secondary.my-2.my-sm-0
          = link_to t('navbar.signin'), new_user_session_path
        %li.btn.btn-secondary.my-2.my-sm-0
          = link_to t('navbar.signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : ENV['APP_NAME']
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Ror Workshops'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .container
        .row
          .col-xs-10.col-xs-offset-1
            = breadcrumbs separator: " &raquo; "
            = yield
    = render 'layouts/footer'